# Generated by Django 5.2.8 on 2025-11-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='sneakers/', verbose_name='Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='game',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='game',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sneaker',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='ShopApp.sneaker', verbose_name='Игра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='sneaker',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='ShopApp.sneaker', verbose_name='Игра'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VideoGame',
        ),
    ]
