# Generated by Django 5.2.8 on 2025-11-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_sneaker_remove_cartitem_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.sneaker', verbose_name='Кроссовки'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='sneaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.sneaker', verbose_name='Кроссовки'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название кроссовок'),
        ),
    ]
