# Generated by Django 5.2.8 on 2025-12-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_alter_cartitem_sneaker_alter_favoriteitem_sneaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='description',
            field=models.CharField(default=None, max_length=300, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
